import { existsSync, readFileSync, readdirSync } from 'node:fs'
import { gunzipSync } from 'node:zlib'
import { NAVIGATION, toDocs, toGuideRedirects } from './generate-config.mjs'
import { DEFAULT_VERSION, VERSIONS, specPath } from './versions.mjs'

// Proves a built dist/ against the navigation tree and versions.mjs. Rerun it
// after any build: `npm run build && npm run build:docs && npm run verify-docs`.

const DIST = 'dist'
const FRAGMENT_DIR = `${DIST}/pagefind/fragment`
const FRAGMENT_PREFIX = 'pagefind_dcd'
// A term the OpenAPI documents carry and no guide mentions, so finding it in a
// reference fragment proves search really reaches the reference. The check below
// re-proves that property against the guide sources on every run.
const REFERENCE_ONLY_TERM = 'prompt_for_number_of_guests'
// Body text from docs/overview.md, so a redirect stub at the root cannot pass.
const ROOT_BODY_TEXT = 'lets your organization integrate with Communal programmatically'
const ROOT_MIN_BYTES = 2000
const ERROR_PAGES = ['400.html', '404.html', '500.html']

const slugify = (str) =>
  str
    .normalize('NFKD')
    .replace(/\p{Diacritic}/gu, '')
    .toLowerCase()
    .replace(/['‘’“”]/g, '')
    .replace(/[^\p{L}\p{N}]+/gu, '-')
    .replace(/^-+|-+$/g, '')

const pagePath = (slug) => (slug === '' ? 'index' : slug)
const pageUrl = (slug) => (slug === '' ? '/' : `/${slug}`)

const listMissing = (missing, total) =>
  `${missing.length} of ${total} missing: ${missing.slice(0, 5).join(', ')}${missing.length > 5 ? ', ...' : ''}`

const results = []
function check(name, run) {
  let problem
  try {
    problem = run()
  } catch (error) {
    problem = error.message
  }
  results.push({ name, problem })
}

// The reference is generated by the OpenAPI plugin, not by the navigation tree,
// so it is not a guide and is skipped wholesale.
const isReference = (slug) => slug === 'reference' || slug.startsWith('reference/')

function prerenderedGuideSlugs(dir = DIST, prefix = '') {
  return readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name
    if (entry.isDirectory()) {
      return isReference(relative) || relative === 'pagefind' || relative === 'assets'
        ? []
        : prerenderedGuideSlugs(`${dir}/${entry.name}`, relative)
    }
    if (!entry.name.endsWith('.html') || ERROR_PAGES.includes(relative)) return []
    const slug = relative === 'index.html' ? '' : relative.replace(/\.html$/, '')
    return isReference(slug) ? [] : [slug]
  })
}

function loadFragments() {
  if (!existsSync(FRAGMENT_DIR)) throw new Error(`${FRAGMENT_DIR} does not exist`)
  return readdirSync(FRAGMENT_DIR)
    .filter((file) => file.endsWith('.pf_fragment'))
    .map((file) => {
      const text = gunzipSync(readFileSync(`${FRAGMENT_DIR}/${file}`)).toString('utf8')
      if (!text.startsWith(FRAGMENT_PREFIX)) {
        throw new Error(`${file} is not prefixed with '${FRAGMENT_PREFIX}'`)
      }
      return JSON.parse(text.slice(FRAGMENT_PREFIX.length))
    })
}

const guides = toDocs(NAVIGATION)
const guideSlugs = guides.map((doc) => doc.slug)
const referencePages = VERSIONS.flatMap((version) => {
  const spec = JSON.parse(readFileSync(specPath(version), 'utf8'))
  const tagPages = (spec.tags ?? []).map((tag) => `reference/${version.date}/${slugify(tag.name)}`)
  const versionPages = [`reference/${version.date}`, ...tagPages]
  if (version.id !== DEFAULT_VERSION.id) return versionPages
  return [
    ...versionPages,
    'reference',
    ...(spec.tags ?? []).map((tag) => `reference/${slugify(tag.name)}`),
  ]
})

const fragments = loadFragments()
const guideFragments = fragments.filter((f) => !f.url.startsWith('/reference'))
const referenceFragments = fragments.filter((f) => f.url.startsWith('/reference'))
const rules = existsSync(`${DIST}/_redirects`)
  ? readFileSync(`${DIST}/_redirects`, 'utf8')
      .split('\n')
      .map((line) => line.trim().split(/\s+/))
      .filter((rule) => rule.length === 3)
  : []
const hasRule = (from, to) =>
  rules.some((rule) => rule[0] === from && rule[1] === to && rule[2] === '301')

check('every navigation doc is prerendered', () => {
  const missing = guideSlugs.filter((slug) => !existsSync(`${DIST}/${pagePath(slug)}.html`))
  return missing.length ? listMissing(missing.map(pageUrl), guideSlugs.length) : null
})

check('no prerendered guide sits outside the navigation tree', () => {
  const known = new Set(guideSlugs)
  const orphans = prerenderedGuideSlugs().filter((slug) => !known.has(slug))
  return orphans.length
    ? `${orphans.map(pageUrl).join(', ')} ${orphans.length === 1 ? 'is' : 'are'} reachable but unreachable from the navigation`
    : null
})

check('the site root serves the overview, not a redirect stub', () => {
  if (!existsSync(`${DIST}/index.html`)) return `${DIST}/index.html is missing`
  const html = readFileSync(`${DIST}/index.html`, 'utf8')
  if (html.length < ROOT_MIN_BYTES) {
    return `${DIST}/index.html is ${html.length} bytes, too small to be a real page`
  }
  return html.includes(ROOT_BODY_TEXT) ? null : `does not contain '${ROOT_BODY_TEXT}'`
})

check('the reference is prerendered for every version and tag', () => {
  const missing = referencePages.filter((page) => !existsSync(`${DIST}/${page}.html`))
  return missing.length ? listMissing(missing, referencePages.length) : null
})

check('Pagefind indexed the guides', () => {
  const indexed = new Set(guideFragments.map((f) => f.url))
  const missing = guideSlugs.map(pageUrl).filter((url) => !indexed.has(url))
  return missing.length ? listMissing(missing, guideSlugs.length) : null
})

check('Pagefind indexed the reference', () => {
  const versions = VERSIONS.filter((v) => v.id !== DEFAULT_VERSION.id)
  const missing = versions
    .map((v) => `/reference/${v.date}/`)
    .filter((prefix) => !referenceFragments.some((f) => f.url.startsWith(prefix)))
  if (referenceFragments.length === 0) return 'no reference fragments in the Pagefind index'
  return missing.length ? `no fragments for ${missing.join(', ')}` : null
})

check(`'${REFERENCE_ONLY_TERM}' is searchable and reaches only the reference`, () => {
  const sources = guides
    .map((doc) => doc.file)
    .filter((file) => readFileSync(file, 'utf8').includes(REFERENCE_ONLY_TERM))
  if (sources.length > 0) {
    return `${sources.join(', ')} now mentions it, so it no longer proves reference coverage; pick another term`
  }
  const inReference = referenceFragments.filter((f) => f.content.includes(REFERENCE_ONLY_TERM))
  const inGuides = guideFragments.filter((f) => f.content.includes(REFERENCE_ONLY_TERM))
  if (inReference.length === 0) {
    return `not found in any of ${referenceFragments.length} reference fragments`
  }
  if (inGuides.length > 0) return `leaked into guide fragments ${inGuides.map((f) => f.url).join(', ')}`
  return null
})

check('the llms artifacts ship at the site root', () => {
  const artifacts = ['llms.txt', 'llms-endpoints.json', 'llms-summary-map.json']
  const missing = artifacts.filter((file) => !existsSync(`${DIST}/${file}`))
  return missing.length ? `missing ${missing.join(', ')}` : null
})

check('_redirects ships the reference splat rules', () => {
  if (rules.length === 0) return `${DIST}/_redirects is missing or empty`
  const required = [
    ['/reference/description/introduction', '/reference'],
    ['/reference/tag/:tag', '/reference/:tag'],
    ['/reference/tag/:tag/*', '/reference/:tag'],
  ]
  const missing = required.filter(([from, to]) => !hasRule(from, to))
  return missing.length ? `missing ${missing.map(([from]) => from).join(', ')}` : null
})

check('_redirects ships a 301 for every non-canonical guide URL', () => {
  const expected = toGuideRedirects(NAVIGATION)
  const missing = expected.filter(([from, to]) => !hasRule(from, to))
  return missing.length ? listMissing(missing.map(([from]) => from), expected.length) : null
})

check('_redirects sends the old /basics to the site root', () =>
  hasRule('/basics', '/') ? null : "no '/basics  /  301' rule")

check('no redirect points at another redirect', () => {
  const sources = new Set(rules.map((rule) => rule[0]))
  const chains = rules.filter((rule) => sources.has(rule[1]))
  return chains.length
    ? chains.map((rule) => `${rule[0]} -> ${rule[1]} -> ...`).join(', ')
    : null
})

const failed = results.filter((r) => r.problem)
for (const { name, problem } of results) {
  console.log(problem ? `FAIL  ${name}\n      ${problem}` : `ok    ${name}`)
}
console.log(
  `\n${results.length - failed.length}/${results.length} checks passed ` +
    `(${guideSlugs.length} guides, ${referencePages.length} reference pages, ${fragments.length} Pagefind fragments)`,
)
process.exit(failed.length ? 1 : 0)
